package enums;

public enum EFonteFosforo {

    OUTRA_FONTE_FOSFORO(0),
    SUPERFOSFATO_SIMPLES_FONT_FOSFORO(1),
    DAP_FONTE_FOSFORO(2),
    FOSFATO_GAFSA_FONTE_FOSFORO(3),
    ESCORIA_DE_THOMAS_FONTE_FOSFORO(4),
    SUPERFOSFATO_TRIPLO_FONTE_FOSFORO(5),
    YOORIN_FONTE_FOSFORO(6),
    FOSFATO_DAOUI_FONTE_FOSFORO(7),
    ACIDO_FOSFORICO_FONTE_FOSFORO(8),
    MAP_FONTE_FOSFORO(9),
    FOSFATO_ARAD_FONTE_FOSFORO(10),
    FOSFATO_PATO_MINAS_FONTE_FOSFORO(11),
    MULTIFOSFATO_MAGNESIANO_FONTE_FOSFORO(12);

    public int descricao;

    EFonteFosforo(int descricao) {
        this.descricao = descricao;
    }
}
